s/_a/A/g; s/^a/A/g
s/_b/B/g; s/^b/B/g
s/_c/C/g; s/^c/C/g
s/_d/D/g; s/^d/D/g
s/_e/E/g; s/^e/E/g
s/_f/F/g; s/^f/F/g
s/_g/G/g; s/^g/G/g
s/_h/H/g; s/^h/H/g
s/_i/I/g; s/^i/I/g
s/_j/J/g; s/^j/J/g
s/_k/K/g; s/^k/K/g
s/_l/L/g; s/^l/L/g
s/_m/M/g; s/^m/M/g
s/_n/N/g; s/^n/N/g
s/_o/O/g; s/^o/O/g
s/_p/P/g; s/^p/P/g
s/_q/Q/g; s/^q/Q/g
s/_r/R/g; s/^r/R/g
s/_s/S/g; s/^s/S/g
s/_t/T/g; s/^t/T/g
s/_u/U/g; s/^u/U/g
s/_v/V/g; s/^v/V/g
s/_w/W/g; s/^w/W/g
s/_x/X/g; s/^x/X/g
s/_y/Y/g; s/^y/Y/g
s/_z/Z/g; s/^z/Z/g
